version: '3.9'

services:
  db:
    image: postgres:13
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      - POSTFRES_HOST=localhost
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prismasql 
      - POSTGRES_DB=tests
    volumes: 
      - pgdata:/data/postgres
    networks:
      - app_net

volumes: 
  pgdata:
    driver: local

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.10.208.0/24"