#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Rodando todos os testes"
echo ""
      
docker-compose up -d 

prismaConnection=true

while $prismaConnection; do
  echo "Connection Prisma..."
  npx dotenv -e .env.test npx prisma migrate dev --name init &&
  prismaConnection=false   

  sleep 1     
done 

npx dotenv -e .env.test jest -i

docker-compose down

echo "Finished!"